title: Aravind
subtitle: "Aravind Reddy V. ECE student of IMTech at IIIT Bangalore"
description: "Student by day, Hacker by night"
author: Aravind Reddy V
language: en
timezone: UTC
url: https://zeroby0.github.io/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/zeroby0/zeroby0.github.io.git

disqus_shortname: aravindvoggu
google_analytics: UA-4910098-10
fb_admins: 100000247608790

twitter: 4ravind
github: zeroby0
email: zerodividedby0@gmail.com
